FROM node:alpine

ENV SERVICE_ID='maana-azure-storage'
ENV REACT_APP_PORTAL_AUTH_DOMAIN='maana.auth0.com'
ENV REACT_APP_PORTAL_AUTH_CLIENT_ID=''
ENV REACT_APP_PORTAL_AUTH_CLIENT_SECRET=''
ENV REACT_APP_PORTAL_AUTH_IDENTIFIER=''
ENV PORT=80

#.env
ENV AZURE_STORAGE_ACCOUNT=
ENV AZURE_STORAGE_ACCESS_KEY=
ENV AZURE_STORAGE_CONNECTION_STRING=

WORKDIR /app

COPY package.json /app
RUN npm install


COPY . /app

CMD npm run dev

EXPOSE 80


